# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./backend
      ATLAS_URI: ${{secrets.ATLAS_URI}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      EMAIL: ${{secrets.EMAIL}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install Packages 
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Run Tests
      run: npm test
      working-directory: ${{env.working-directory}}
